/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppVehiclesRouteImport } from './routes/_app.vehicles'
import { Route as AppTripsRouteImport } from './routes/_app.trips'
import { Route as AppReportsRouteImport } from './routes/_app.reports'
import { Route as AppMaintenanceRouteImport } from './routes/_app.maintenance'
import { Route as AppExpensesRouteImport } from './routes/_app.expenses'
import { Route as AppDriversRouteImport } from './routes/_app.drivers'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppVehiclesRoute = AppVehiclesRouteImport.update({
  id: '/vehicles',
  path: '/vehicles',
  getParentRoute: () => AppRoute,
} as any)
const AppTripsRoute = AppTripsRouteImport.update({
  id: '/trips',
  path: '/trips',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppMaintenanceRoute = AppMaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => AppRoute,
} as any)
const AppExpensesRoute = AppExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => AppRoute,
} as any)
const AppDriversRoute = AppDriversRouteImport.update({
  id: '/drivers',
  path: '/drivers',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/drivers': typeof AppDriversRoute
  '/expenses': typeof AppExpensesRoute
  '/maintenance': typeof AppMaintenanceRoute
  '/reports': typeof AppReportsRoute
  '/trips': typeof AppTripsRoute
  '/vehicles': typeof AppVehiclesRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/drivers': typeof AppDriversRoute
  '/expenses': typeof AppExpensesRoute
  '/maintenance': typeof AppMaintenanceRoute
  '/reports': typeof AppReportsRoute
  '/trips': typeof AppTripsRoute
  '/vehicles': typeof AppVehiclesRoute
  '/': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/drivers': typeof AppDriversRoute
  '/_app/expenses': typeof AppExpensesRoute
  '/_app/maintenance': typeof AppMaintenanceRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/trips': typeof AppTripsRoute
  '/_app/vehicles': typeof AppVehiclesRoute
  '/_app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/drivers'
    | '/expenses'
    | '/maintenance'
    | '/reports'
    | '/trips'
    | '/vehicles'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/drivers'
    | '/expenses'
    | '/maintenance'
    | '/reports'
    | '/trips'
    | '/vehicles'
    | '/'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/drivers'
    | '/_app/expenses'
    | '/_app/maintenance'
    | '/_app/reports'
    | '/_app/trips'
    | '/_app/vehicles'
    | '/_app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/vehicles': {
      id: '/_app/vehicles'
      path: '/vehicles'
      fullPath: '/vehicles'
      preLoaderRoute: typeof AppVehiclesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/trips': {
      id: '/_app/trips'
      path: '/trips'
      fullPath: '/trips'
      preLoaderRoute: typeof AppTripsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/maintenance': {
      id: '/_app/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof AppMaintenanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/expenses': {
      id: '/_app/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof AppExpensesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/drivers': {
      id: '/_app/drivers'
      path: '/drivers'
      fullPath: '/drivers'
      preLoaderRoute: typeof AppDriversRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppDriversRoute: typeof AppDriversRoute
  AppExpensesRoute: typeof AppExpensesRoute
  AppMaintenanceRoute: typeof AppMaintenanceRoute
  AppReportsRoute: typeof AppReportsRoute
  AppTripsRoute: typeof AppTripsRoute
  AppVehiclesRoute: typeof AppVehiclesRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDriversRoute: AppDriversRoute,
  AppExpensesRoute: AppExpensesRoute,
  AppMaintenanceRoute: AppMaintenanceRoute,
  AppReportsRoute: AppReportsRoute,
  AppTripsRoute: AppTripsRoute,
  AppVehiclesRoute: AppVehiclesRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
